[package]
name = "monkey"
version = "0.2.3"
authors = ["ktanaka101 <kentanaka101@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"
thiserror = "2.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "fibonacci"
harness = false
