[package]
name = "monkey"
version = "0.1.0"
authors = ["ktanaka101 <kentanaka101@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "fibonacci"
harness = false